### ISSUE TITLE
Install the WW15MGH.DAC file and part of the installation process

### ISSUE THREAD

**Issue by pjalocha** [VirusPilot/ogn-pi4#1]
as part of the installation you could download the EGM96 file like this:

wget --no-check-certificate http://earth-info.nga.mil/GandG/wgs84/gravitymod/egm96/binary/WW15MGH.DAC

into the same directory where the binaries are.
This avoids the need to specify GeoidSepar thus simplifies the installation process.
GeoidSepar you can remove or comment out of the configuration file.

**Comment by VirusPilot** [comment]
Thanks for this proposal, will check and include it then.

**Comment by VirusPilot** [comment]
Is included from now on.
